  data:
    build: data/dockerfiles/data
    volumes:
      - ${PWD}/www:/var/www

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
    volumes:
      - ${PWD}/data/mysql:/etc/mysql/conf.d

  php:
    build: data/dockerfiles/php-fpm
    ports:
      - 9000:9000
    volumes_from:
      - data
    links:
      - mysql
      - elasticsearch

  nginx:
    build: data/dockerfiles/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes_from:
      - data

  adminer:
      image: clue/adminer
      ports:
        - 8081:80
      links:
        - mysql

  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.bind_host=0.0.0.0 --http.cors.enabled=true --http.cors.allow-origin=*
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${PWD}/data/elasticsearch/config:/usr/share/elasticsearch/config
      - ${PWD}/data/elasticsearch/data:/usr/share/elasticsearch/data